1:
  target: 0.90
  min: 0.59
  max: 1.35
2:
  target: 0.95
  min: 0.62
  max: 1.43
3:
  target: 1.00
  min: 0.65
  max: 1.50
4:
  target: 1.05
  min: 0.68
  max: 1.58
5:
  target: 1.10
  min: 0.72
  max: 1.65
6:
  target: 1.15
  min: 0.75
  max: 1.73
7:
  target: 1.20
  min: 0.78
  max: 1.80
